### ISSUE TITLE
Assignment-3 is reading for grading 

### ISSUE THREAD

**Issue by jiwonpark1994** [VIS-2129-F2020/jiwonpark-vis#6]
Hello Carole and Alex,
My assignment-3 (https://vis-2129-f2020.github.io/jiwonpark-vis/VIS-Assignment-3.html) is ready for grading.
I hope you enjoy my work and look forward to hearing your feedback!

Best,
Jiwon

**Comment by bauranov** [comment]
Everything looks great, nicely done!
