### ISSUE TITLE
Question for VIS assignment-4

### ISSUE THREAD

**Issue by jiwonpark1994** [VIS-2129-F2020/jiwonpark-vis#8]
Hello Carole and Alex,

I was finishing my VIS assignment-4 (https://vis-2129-f2020.github.io/jiwonpark-vis/Assignment-4.Rmd), and I had a problem that I couldn't figure out by myself after holding this for more than one hour :( 

My problem is the line 152-220, calculating the number of south Boston trees within the walkshed. I think I did all correctly, but it is showing all-Boston tree data constantly, and some codes (especially joining the data frame part) get errors. Could you please take a look at what is the problem? I'm worried that I can imagine I might have done something really silly, but I didn't have any other measures to find out myself.

Thank you and I look forward to hearing from you!
Jiwon

**Comment by c-voulgaris** [comment]
When you run line 160, you get an error that says:

```
Error in st_geos_binop("intersects", x, y, sparse = sparse, prepared = prepared, : st_crs(x) == st_crs(y) is not TRUE
```
That last part `st_crs(x) == st_crs(y) is not TRUE` is telling you that the two layers you're using for the spatial subsetting are not in the same coordinate system. Your Boston neighborhood boundaries are in lat/lon coordinates and you've transformed your trees to be in State Plane coordinates. If you want to transform the points until after your do the subsetting, the subset should work. So you'd just move line 156 to be after line 160.
